feat: Добавить функционал запросов вещей и ответов на запросы. Добави…
denis-shishki/java-shareit pull request #3
Opened 2023-11-30 20:34 UTC by denis-shishki

…ть пагинацию в запросы Get

2023-12-03 05:06 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
>  }
Нужно добавить обработку Throwable в статус 500

2023-12-03 05:17 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
booking.setId(0L); делать не нужно. 
По второму вопросу: можно использовать как примитивный тип так и объектный. Они замяпятся в колонку БД одинаково.
Но объектный тип может быть nullable, и если колонка без NOT NULL , то логично в данной ситуации использовать объектный тип, чтобы созхранить семантику меджу джавой и БД.

2023-12-03 05:19 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>          switch (state) {
Нужно использовать перечислимое вместо строки

2023-12-03 05:22 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
Вы прошли @Transactional и нужно пробовать использовать (для данной бизнес логики не особо обязательна, но попрактиковаться нужно)

2023-12-03 05:26 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>      private final ItemRepository itemRepository;
ItemRepository itemRepository лишнее поле, нужно постараться все сделать через ItemService

2023-12-03 05:27 UTC, VadimZharkov commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    @SneakyThrows
Это осознанно применяешь (понимаешь как работает)?

2023-12-03 05:33 UTC, VadimZharkov commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +    @Transactional
`@DataJpaTest`  добавляет `@Transactional` в каждый метод по умолчанию, поэтому руками нет необходимости прописывать

2023-12-03 05:34 UTC, VadimZharkov commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +        Mockito.verify(requestService, Mockito.times(1)).createRequest(userId, itemRequestDto);
Хорошо что и Mockito.verify заюзал

2023-12-03 05:42 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>              throw new ValidationException("Не указан период аренды");
Лучше правильность заполнения полей входных данных (dto) проверять в начале метода, потому как если они не соответствуют ожиданиям, то и не нудно дальше делать запросов к БД.
Также возможно не заострялось в теории, но можно проверку полей объектов dto сделать альтернативным способом с помошью аннотаций @Valid, @NotNull и т.д. Советую освоить и применить в дальнейшем, потому как часто используется на практике.

2023-12-03 05:42 UTC, VadimZharkov requested changes
Можно улучшить

2023-12-03 11:34 UTC, denis-shishki commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    @SneakyThrows
Применение этой аннотации увидел в вебинаре Глеба Шишкова по 15 спринту про Mock тестирование. 
В mockMvc.perform(...) может возникнуть Exception и вместо блока try catch или добавления исключения в сигнатуру метода можно использовать @SneakyThrows

2023-12-03 11:48 UTC, denis-shishki commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>              throw new ValidationException("Не указан период аренды");
Замечал эти аннотации у других. Хочется ими воспользоваться, но пока нет времени углубляться. Обязательно ознакомлюсь.

2023-12-03 13:17 UTC, denis-shishki commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
Если удаляем в 34 строке booking.setId(0L); то поле User booker из метода save(..) вернется с пустыми полями. Если Сделать в сущности Booking поле id не Long, а примитивом long, то тоже самое.
Единственный выход сейчас вижу, это запрашивать у базы данных целиком user по userId и уже его вкладывать в Booking, но мне такой выход не нравится
![скрин](https://github.com/denis-shishki/java-shareit/assets/126517333/1b8e31f1-4cc6-458a-bbe6-a97f79d77ca8)

2023-12-03 13:32 UTC, denis-shishki commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
Причем в дебаггере видно, что и поле Item тоже не заполняется.
Пока решил оставить booking.setId(0L) т.к. нам не нужно делать дополнительные запросы в бд чтобы заполнить User перед сохранением

2023-12-04 06:46 UTC, VadimZharkov approved these changes

2023-12-10 18:05 UTC, merged